default:
  image: swift
  tags:
    - size:2xlarge
    - arch:amd64

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
    - if: $CI_COMMIT_REF_NAME == "main"
      when: always
    - when: never

# Check merge request message
lint:
  stage: build
  script:
    - echo Start PR Validation
    - env
    - '[[ "$CI_COMMIT_MESSAGE" =~ ^(feat|fix|chore|docs|tests|ci) ]] || (echo "no commit type is specified in merge request title" && exit 1)'



