# Do not specify an `included` section at this top-level file. Specify the
# `--config` option pointing to this file, and the `--path` option to the files
# you wish to lint

excluded:
  - Pods
  - .build
  - Tests

analyzer_rules:
  - unused_import
  - unused_declaration

opt_in_rules:
  - empty_count

disabled_rules:
  - opening_brace

# configurable rules can be customized from this configuration file
closing_brace: error
colon:
  severity: error
comma: error
empty_enum_arguments: error
function_body_length:
  warning: 100
  error: 150
identifier_name:
  excluded:
    - id
    - of
    - or
  allowed_symbols:
    - _
  validates_start_with_lowercase: false
line_length:
  warning: 120
  error: 160
return_arrow_whitespace: error
statement_position:
  severity: error
todo: warning
trailing_semicolon: error
