name: Swift SDK Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  code-lint:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Run swiftformat
        run: swiftformat .
      - name: Run swiftlint
        run: swiftlint
