name: Swift SDK Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Run test
        run: xcodebuild test -scheme aws-solution-clickstream-swift -destination 'platform=iOS Simulator,name=iPhone 14 Pro,OS=latest' -resultBundlePath .build/test/TestResults.xcresult | xcpretty --simple --color --report junit
      - name: Upload Test Report
        uses: codecov/codecov-action@v3
        with:
          name: report
          files: .build/test/TestResults.xcresult
          swift: true
          
